#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

module load salmon

salmon alevin -l ISR \
-1 /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz \
-2 /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_2.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_2.fastq.gz /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_2.fastq.gz \
--whitelist /projectnb/bf528/users/group_5/project_4/data_curator/whitelist_barcodes.txt \
--end 5 --barcodeLength 19 --umiLength 6 -i /projectnb/bf528/users/group_5/project_4/data_curator/salmon_index_gencode_flag/ \
-o /projectnb/bf528/users/group_5/project_4/data_curator/salmon_output/ -p 16 --tgMap /projectnb/bf528/users/group_5/project_4/data_curator/txp_to_gene.tsv

echo "Job finished: $(date +%F)" 

