#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"


# unzip all files
# SAMPLE 1
gzip -dc /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879604/SRR3879604_1_bc.fastq.gz > /projectnb/bf528/users/group_5/project_4/data_curator/fastq_files/SRR3879604_1_bc.fastq

echo "finished unzipping sample 1"

gzip -dc /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879605/SRR3879605_1_bc.fastq.gz > /projectnb/bf528/users/group_5/project_4/data_curator/fastq_files/SRR3879605_1_bc.fastq

echo "unzipped the second sample"

gzip -dc /projectnb/bf528/project_4_scrnaseq/fastq/SRR3879606/SRR3879606_1_bc.fastq.gz > /projectnb/bf528/users/group_5/project_4/data_curator/fastq_files/SRR3879606_1_bc.fastq

echo "unzipped the 3rd sample"


echo "Job finished: $(date +%F)"
