#!/bin/bash -l


#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# Generate individual white list
awk '$2 >= 180 {print $1}' /projectnb/bf528/users/group_5/project_4/data_curator/grouped_barcodes.txt > /projectnb/bf528/users/group_5/project_4/data_curator/whitelist_barcodes.txt

echo "Job finished: $(date +%F)"
